# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vegetables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temp', models.IntegerField()),
                ('max_temp', models.IntegerField()),
                ('message', models.TextField()),
                ('vegetable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegetables.Vegetable')),
            ],
        ),
    ]
