# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='vegetable_id',
            new_name='vegetable',
        ),
    ]
